version: '3'

services:

  mysql_db:
    image: mysql:5.7
    container_name: documan-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: RVf3pk0p5jKWYH06XHMcIbMGYO8AY0
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: Watyaa21
      MYSQL_DATABASE: documan_db
    ports:
      - "3308:3306"
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
